import { BarChart2, Code2, Feather, FileJson, Grid, HandCoins, HelpCircle, LayoutGrid, MemoryStick, ReceiptText, StickyNote, Swords, UtensilsCrossed, Wallet2, type LucideIcon } from 'lucide-react';

export interface AppInfo {
    name: string;
    path: string;
    url: string;
    tag: string;
    image: string;
    visible: boolean;
    description: string;
    techStack: string[];
    icon: LucideIcon;
}

export const Apps: AppInfo[] = [
    {
        name: 'Formlyst',
        path: '/formlyst',
        url: import.meta.env.VITE_URL_FORMLYST,
        tag: 'Drag-and-drop form builder',
        image: '/cover/formlyst.webp',
        visible: true,
        description: 'Build multi-step forms with nested sections, drag fields into place, and publish a shareable link. Responses come back to a per-form dashboard.',
        techStack: ['dnd-kit', 'React Hook Form', 'Yup', 'TanStack Query'],
        icon: StickyNote,
    },
    {
        name: 'Invoice Studio',
        path: '/invoice',
        url: import.meta.env.VITE_URL_INVOICE,
        tag: 'Build invoices, export PDF',
        image: '/cover/invoice.webp',
        visible: true,
        description: 'Fill in billing details and line items, watch a live preview update as you type, then download a print-ready PDF rendered by a Python serverless function.',
        techStack: ['FastAPI', 'ReportLab', 'Vercel Serverless', 'React 19'],
        icon: ReceiptText,
    },
    {
        name: 'Pokeverse',
        path: '/pokeverse',
        url: import.meta.env.VITE_URL_POKEVERSE,
        tag: 'Pokédex meets battle simulator',
        image: '/cover/battle-sim2.webp',
        visible: true,
        description: 'A virtualized Pokédex on top of PokéAPI, plus a turn-based battle flow — pick a team, queue moves, watch the simulator play it out.',
        techStack: ['PokéAPI', 'TanStack Query', 'Redux Toolkit', 'Recharts'],
        icon: Swords,
    },
    {
        name: 'Super Tic-Tac-Toe',
        path: '/super-tic-tac-toe',
        url: import.meta.env.VITE_URL_SUPER_TIC_TAC_TOE,
        tag: 'Tic-tac-toe with a twist',
        image: '/cover/tictactoe.webp',
        visible: true,
        description: 'A 3x3 grid of tic-tac-toe boards where your move forces the board your opponent plays on next. Local two-player.',
        techStack: ['React 19', 'TypeScript', 'Tailwind CSS'],
        icon: Grid,
    },
    {
        name: 'Blogify',
        path: '/blogify',
        url: import.meta.env.VITE_URL_BLOGIFY,
        tag: 'Blogs and curated notebooks',
        image: '/cover/blogger.webp',
        visible: true,
        description: 'Write rich-text posts with Tiptap, group them into shareable notebooks, and browse an author-discovery feed.',
        techStack: ['Tiptap', 'TanStack Query', 'JWT Auth', 'ImgBB'],
        icon: Feather,
    },
    {
        name: 'BudgetBuddy',
        path: '/budgetbuddy',
        url: import.meta.env.VITE_URL_BUDGET_BUDDY,
        tag: 'Track spending, see the trends',
        image: '/cover/budget.webp',
        visible: true,
        description: 'Log expenses across categories, scan a running ledger, and break down spending by month, category, or tag with interactive charts.',
        techStack: ['Recharts', 'TanStack Query', 'React Hook Form'],
        icon: Wallet2,
    },
    {
        name: 'Sorting Visualizer',
        path: '/sorting-visualizer',
        url: import.meta.env.VITE_URL_SORTING_VISUALIZER,
        tag: 'Algorithms, frame by frame',
        image: '/cover/sorting.webp',
        visible: true,
        description: 'Step through six classic sorting algorithms with adjustable speed and a live counter for comparisons and swaps.',
        techStack: ['Algorithm Visualization', 'requestAnimationFrame', 'TypeScript'],
        icon: BarChart2,
    },
    {
        name: 'Poke-Memory',
        path: '/poke-memory',
        url: import.meta.env.VITE_URL_POKE_MEMORY,
        tag: "Match the pairs, catch 'em all",
        image: '/cover/memory.webp',
        visible: true,
        description: 'A Pokémon-themed memory matching game — pick a difficulty, flip cards, find pairs, and chase your best time.',
        techStack: ['PokéAPI', 'Redux Toolkit', 'CSS Animations'],
        icon: MemoryStick,
    },
    {
        name: 'Loan Wizard',
        path: '/loan-wizard',
        url: import.meta.env.VITE_URL_LOAN_WIZARD,
        tag: 'EMI calculator + affordability check',
        image: '/cover/loan.webp',
        visible: true,
        description: 'Compute EMIs with a full amortization breakdown, or flip into reverse mode to see what loan your income can actually carry.',
        techStack: ['Recharts', 'Financial Math', 'TypeScript'],
        icon: HandCoins,
    },
    {
        name: 'JSON Visualizer',
        path: '/json',
        url: import.meta.env.VITE_URL_JSON,
        tag: 'Explore deeply nested JSON',
        image: '/cover/json.webp',
        visible: true,
        description: 'Paste, upload, or fetch JSON and walk through it as a collapsible tree, with breadcrumbs that track exactly where you are in the structure.',
        techStack: ['Recursive Tree View', 'Breadcrumb Routing', 'TypeScript'],
        icon: FileJson,
    },
    {
        name: 'Markdown Live',
        path: '/markdown',
        url: import.meta.env.VITE_URL_MARKDOWN,
        tag: 'Two-pane Markdown editor',
        image: '/cover/markdown.webp',
        visible: true,
        description: 'Write GitHub-flavored Markdown on the left, see it rendered on the right. Dark mode, syntax highlighting, and one-click clipboard export.',
        techStack: ['marked', 'GFM', 'Tailwind Typography'],
        icon: Code2,
    },
    {
        name: 'Sudoku',
        path: '/sudoku',
        url: import.meta.env.VITE_URL_SUDOKU,
        tag: 'Generated puzzles with animated solver',
        image: '/cover/sudoku.webp',
        visible: true,
        description: 'Solve a fresh puzzle with conflict highlighting, peer-cell guides, and keyboard navigation — or hit Solve to watch a backtracking algorithm work through it step by step.',
        techStack: ['Backtracking', 'Generators', 'Custom Hooks'],
        icon: LayoutGrid,
    },
    {
        name: 'Quizzo',
        path: '/quizzo',
        url: import.meta.env.VITE_URL_QUIZZO,
        tag: 'Timed trivia, scored results',
        image: '/cover/quiz.webp',
        visible: true,
        description: 'Pick a topic and length, answer timed questions from the Open Trivia DB, and get a scored breakdown at the end.',
        techStack: ['Open Trivia DB', 'Redux Toolkit', 'Timer Logic'],
        icon: HelpCircle,
    },
    {
        name: 'Recipe Haven',
        path: '/recipe-haven',
        url: import.meta.env.VITE_URL_RECIPE_HAVEN,
        tag: 'Browse and search recipes',
        image: '/cover/recipe.webp',
        visible: true,
        description: 'A recipe browser on top of TheMealDB — search by name, filter by category, area, or alphabet, then drill into full ingredients and steps.',
        techStack: ['TheMealDB', 'TanStack Query', 'Dynamic Routing'],
        icon: UtensilsCrossed,
    },
];
